//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieBookingSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MovieBookingSystemEntities2 : DbContext
    {
        public MovieBookingSystemEntities2()
            : base("name=MovieBookingSystemEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cart> cart { get; set; }
        public virtual DbSet<cinema> cinema { get; set; }
        public virtual DbSet<movie> movie { get; set; }
        public virtual DbSet<ticket> ticket { get; set; }
        public virtual DbSet<user_> user_ { get; set; }
    }
}
